FROM debian:10

RUN sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list \
 && sed -i 's/security.debian.org/archive.debian.org/g' /etc/apt/sources.list \
 && apt-get update -y \
 && apt-get install -y qt5-default

WORKDIR /usr/local/src/
COPY libs/linux libs
ENV LD_LIBRARY_PATH=/usr/local/src/libs

WORKDIR /usr/local/src/net_point_matching/
COPY package/*.deb .
COPY config/*.ini ./config/

RUN rm -f ./config/db_conf* \
 && dpkg -i *.deb \
 && rm *.deb