FROM libepg

RUN apt-get update -y \
 && apt-get -y install g++ \
                       gcc \
                       cmake \
                       make \
                       gdb \
 && rm -rf /var/lib/apt/lists/*

# pour que gdb ne se link pas aux libs conda importées
ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
 
ENV APP_DIR_SRC=/usr/local/src/net_point_matching/                                                 

WORKDIR $APP_DIR_SRC

