FROM libepg

RUN sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list \
 && sed -i 's/security.debian.org/archive.debian.org/g' /etc/apt/sources.list \
 && apt-get -y update \
 && apt-get -y install gdb

ENV APP_DIR_SRC=/usr/local/src/net_point_matching/                                                     

WORKDIR $APP_DIR_SRC

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/src/sd-externs/unix-gxx/gmp-6.1.2/lib:/usr/local/src/sd-externs/unix-gxx/mpfr-4.1.0/lib:/usr/local/src/sd-externs/unix-gxx/shapelib-1.3.0b3/lib:/usr/local/src/sd-externs/unix-gxx/qt-5.14.1/lib/:/usr/local/src/sd-externs/unix-gxx/sqlite-3.32.3/lib